language: java
jdk:
  - oraclejdk8
os:
  - linux
env: 
  - SOURCE_DIR_1=001-Lazy
  - SOURCE_DIR_1=myVcs
script:
  - cd $SOURCE_DIR_1 && gradle check
  - cd ..
  - cd $SOURCE_DIR_2 && gradle check
  
  
